spring.application.name=quality-accreditation-system

server.port=9091

# Database Connection
spring.datasource.url=${QAC_DB_URL}
spring.datasource.username=${QAC_DB_USERNAME:root}
spring.datasource.password=${QAC_DB_PASSWORD:root}

# Hibernate (JPA) configs
spring.jpa.hibernate.ddl-auto=${QAC_DDL_AUTO:validate}
spring.jpa.show-sql=${QAC_SHOW_SQL:FALSE}

# JWT Secret
jwt.secret-key=${QAC_JWT_SECRET_KEY}
jwt.access-expiration=${QAC_JWT_ACCESS_EXPIRATION:900000}
jwt.refresh-expiration=${QAC_JWT_REFRESH_EXPIRATION:604800000}